name = "ConstraintCommons"
uuid = "e37357d9-0691-492f-a822-e5ea6a920954"
authors = ["azzaare (jean-François BAFFIER)"]
version = "0.1.2"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"

[compat]
Dictionaries = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
